version: '3'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /food_professor/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/food_professor
      - ./api/vendor/bundle:/food_professor/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/food_professor
    command: sh -c "cd react-app && yarn start"
    ports:
      - "8000:3000"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: